name: Deploy Laravel to Rumahweb

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Upload via FTP
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: Upload to hosting
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # folder project di GitHub
          server-dir: /api-backend  # folder Laravel di hosting
